### ISSUE TITLE
Improvement suggestions 

### ISSUE THREAD

**Issue by Cpt-Hazama** [DrVrej/VJ-Base#100]
First things first, all these years and no CustomOnDangerDetected 😔 to make it to where we are not double checking dangers/grenades, this should be an easy implementation to the base so we don't have to override an entire function just for grenade related stuff.

Secondly, a major visual enhancement could be done to the human base. Currently, the human NPCs constantly snap their angle towards the enemy. This creates an unpleasant and unrealistic look to them, while also simultaneously disallowing the use of **yaw** pose parameters. Something that I did for my base, as well as Silverlan's unreleased human base, is that human NPCs were disallowed to face a enemy if they were still within 45 degrees of the front of them. Not only does this allow the use of yaw pose parameters, but as seen in both our bases they can utilize turn animations which look fabulous on top of not snapping towards the enemy.

Lastly, **please revamp the grenade code after all these years. I need event support** 😭

**Comment by DrVrej** [comment]
Added `CustomOnDangerDetected` in 1e50651605512ef3b7ed976edd0a8544fdb2acb1

**Comment by DrVrej** [comment]
As of the latest commit 9aebb1dcbbaf9790c27409757129c5f0f1596b5c, all the suggestions have been completed!
