### ISSUE TITLE
Dedicated server issue while using VJ Base

### ISSUE THREAD

**Issue by IIMKII** [DrVrej/VJ-Base#103]
When I run VJ-Base on a dedicated server, I tried both fast dl and workshop and im always having issues with errors and not being able seeing some of the weapons and most thumbnails.

When I go and subscribe to vjbase via the workshop and then join the server, everything works as intended.

Not sure why I cant load vjbase without having to subscribe to it, the server seems like its only sending so much, I know the filesize of vj-base exceeds 64mb , I tried cutting it in half for fast dl and that still didnt work.

The only solution is to subscribe to the addon via workshop before joining the server

In the end both your client and the server have to have it installed, and you need to manually go and subscribe to it , not just let the server handle it like all other mods

If it makes any difference, I am running this on darkrp gamemode

**Comment by DrVrej** [comment]
I don't run servers so I can't help you much, but I do know that this isn't something to do with the mod itself. All servers should have a workshop collection where the players can easily subscribe to all the workshop items, including VJ Base.
