### ISSUE TITLE
DrVrej tab in spawn menu is a super wide camera from my characters perspective

### ISSUE THREAD

**Issue by neepha99** [DrVrej/VJ-Base#106]
![image](https://github.com/DrVrej/VJ-Base/assets/125772309/df0dd367-84fb-4c64-a587-eb8f99aa39d5)
The tab for changing VJ-Base settings is some sort of copy of my character's view and it's incredibly wide, which is a bit inconvenient when I want to navigate around other tabs. It seems somewhat random and I'm unsure what's causing it.

**Comment by DrVrej** [comment]
I have never seen anything like this nor would it make sense. I am simply using GMod's functions to add spawn menu items, this isn't an issue from VJ Base. You most likely have an addon overriding default GMod code or your game is corrupted.
