### ISSUE TITLE
Change base_gmodentity to base_entity (If possible without issues)

### ISSUE THREAD

**Issue by oNyaaaa** [DrVrej/VJ-Base#110]
ERROR: Trying to derive entity obj_vj_projectile_base from non existant entity base_gmodentity! (x6)
ERROR: Trying to derive entity sent_vj_ply_spawnpoint from non existant entity base_gmodentity!
ERROR: Trying to derive entity obj_vj_flareround from non existant entity base_gmodentity!
ERROR: Trying to derive entity obj_vj_projectile_base from non existant entity base_gmodentity! (x13)
ERROR: Trying to derive entity obj_vj_gib from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_vj_board from non existant entity base_gmodentity!
ERROR: Trying to derive entity obj_vj_projectile_base from non existant entity base_gmodentity! (x6)
ERROR: Trying to derive entity prop_vj_animatable from non existant entity base_gmodentity!
ERROR: Trying to derive entity obj_vj_projectile_base from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_vj_fireplace from non existant entity base_gmodentity!
ERROR: Trying to derive entity sent_vj_adminhealthkit from non existant entity base_gmodentity!
ERROR: Trying to derive entity prop_vj_animatable from non existant entity base_gmodentity!
ERROR: Trying to derive entity obj_vj_projectile_base from non existant entity base_gmodentity! (x12)

Because base_gmodentity is called base_entity

**Comment by DrVrej** [comment]
This is happening because you are attempting to use the base outside of Sandbox derived gamemode. I'll look into converting them to regular entities, but it's best to use VJ Base in sandbox derived gamemodes only.

**Comment by oNyaaaa** [comment]
Thank you.

**Comment by DrVrej** [comment]
Changed all the entities that use `base_gmodentity` to `base_anim` in 0892702a9e3a1bde7567442490ed6e071b464f7c, this will be included in the next major update on the workshop, thank you for reporting this!

**Comment by oNyaaaa** [comment]
np
