### ISSUE TITLE
NPCs freezing when not given personal space

### ISSUE THREAD

**Issue by Bigboibigdum** [DrVrej/VJ-Base#111]
VJ NPCs keep losing the ability to move when getting too close to each other. This happens with different NPC addons so I think it's an issue with the base.
![image](https://github.com/DrVrej/VJ-Base/assets/87398673/6759054f-fb84-456f-be95-4dedefc4613b)

**Comment by Bigboibigdum** [comment]
Oh yeah I find it commonly when npcs are following you

**Comment by DrVrej** [comment]
Thanks for the report, this issue was fixed months ago, it will be pushed on Steam Workshop once the update is released later this year 👍
