### ISSUE TITLE
bug with VJ and Zbase squads

### ISSUE THREAD

**Issue by icu8some2** [DrVrej/VJ-Base#112]
This error occurs when you attempt to kill a VJ npc that shares a squad with a zbase npc. VJ base npc becomes immortal. 

[VJ Base] lua/entities/npc_vj_human_base/init.lua:3869: attempt to call method 'CustomOnAllyDeath' (a nil value)
  1. PriorToKilled - lua/entities/npc_vj_human_base/init.lua:3869
   2. unknown - lua/entities/npc_vj_human_base/init.lua:3845

**Comment by DrVrej** [comment]
Zbase directly copied variables from VJ Base, thus causing unintended conflictions such as this. Should be fixed in this commit: 01c5d0472f982b10f88fde29617984d9489c12a4 (To be included in the upcoming update)
