### ISSUE TITLE
VJ.SET broken?

### ISSUE THREAD

**Issue by Bigboibigdum** [DrVrej/VJ-Base#113]
I'm making a vj base npc with the creature base but it gives me an error saying SET is nil when trying to set the time between heals with the npc being a medic. 

yeah i dont know what else to say whats up with that

**Comment by Bigboibigdum** [comment]
Seems like it happens with any of the properties containing VJ.SET

**Comment by DrVrej** [comment]
You're attempting to use an NPC that you made on the VJ Base Revamp with the workshop version of VJ Base. Either make it on the workshop version or download the revamp (GitHub) version locally onto your game and disable the workshop version.

**Comment by Bigboibigdum** [comment]
wait how do i get the workshop dummy file then

**Comment by Bigboibigdum** [comment]
well of course it wont be on the workshop i mean the version on github that matches the most recent release
