### ISSUE TITLE
Can't change idle/walk/running animations.

### ISSUE THREAD

**Issue by MagicalFruitBasket** [DrVrej/VJ-Base#114]
i.e. stuff like 
ENT.AnimTbl_Walk = {ACT_RUN} 
doesn't seem to work anymore.

**Comment by DrVrej** [comment]
The revamp version of VJ Base now uses translation system instead, the same system that HL1 and HL2 NPCs run on, so variables like `AnimTbl_Walk` are now removed. If you have experience with making NPCs on the source engine, then this will be straight forward. If you have no such experience, then I recommend looking at official packs that have been updated to the revamp version to see how it works. For example: https://github.com/DrVrej/Zombie-SNPCs
