### ISSUE TITLE
Is there any way to make the SNPCS less overpowered?

### ISSUE THREAD

**Issue by postredaction** [DrVrej/VJ-Base#119]
At first i thought it was just sentry's, but it seems as if every gun VJ Base SNPC is aimbotting. It is impossible to peek a corner without the NPC locking on the moment i peek and headshotting me. Can this be edited/changed in some way at the moment? I tried looking for a difficulty option, but the one right now just reduces health and damage, instead of aiming proficiency.

Edit: I actually just now realized that Sentry's SNPCS actually do have a configurable weapon accuracy slider, but that seems to be done by him only sadly.

**Comment by DrVrej** [comment]
Hello, I recommend reading my reply in #116 it addresses this issue. However keep in mind that's specifically for human NPCs, other NPCs like sentries aren't controlled by VJ Base, that's fully controlled by the developer. Since this is mostly a duplicate, I'll close the issue 👍
