### ISSUE TITLE
Post-Eating Timer Value

### ISSUE THREAD

**Issue by epicplayer40** [DrVrej/VJ-Base#122]
When a SNPC is done eating, they will always wait at least 30 seconds before checking if they can eat again. I think this value should be editable so creators can decide how long the SNPC will wait before eating again.
https://github.com/DrVrej/VJ-Base/blob/4c0da7bc04311dcb569ab119c5132d5600fca3c0/lua/entities/npc_vj_creature_base/init.lua#L2025C11-L2025C46

**Comment by DrVrej** [comment]
Added `self.NextEatTime` in f742706b85d280aea9e2e267315680d6a3753f58, defaults to `30` seconds
