### ISSUE TITLE
Swapping Controller NPC Forgets the Camera Mode

### ISSUE THREAD

**Issue by epicplayer40** [DrVrej/VJ-Base#123]
If a player-controlled SNPC is coded so that it swaps the player to another NPC, the VJC_Camera_Mode of the controller will reset to whatever default value the NPC wants rather than keeping the camera that was used for the previous NPC.

An example would be if the player is controlling a zombie in first person (from HLZE SNPCs), then detatches the headcrab (switching the controller to the new headcrab NPC), the player's camera will reset to third person rather than keeping the camera mode that the previous NPC was using.

**Comment by DrVrej** [comment]
Not something that can be done properly through the base, especially when it's meant for a custom code. I recommend just setting it when you create the new controller in your swapping system
