### ISSUE TITLE
Lua error in server log

### ISSUE THREAD

**Issue by Weapon317** [DrVrej/VJ-Base#125]
After downloading the new version of VJ base from the git, I am getting this error consistently within my server logs:

[vj_base] addons/vj_base/lua/entities/npc_vj_creature_base/init.lua:1206: attempt to call method 'GetBoneFollowers' (a nil value)
  1. unknown - addons/vj_base/lua/entities/npc_vj_creature_base/init.lua:1206

**Comment by DrVrej** [comment]
You need the new version of GMod to use the GitHub version, either wait for the GMod update to be released or use dev version of GMod or use workshop version of VJ Base
