### ISSUE TITLE
Timer Failed / GetBoneFollowers Error

### ISSUE THREAD

**Issue by ZombieWars** [DrVrej/VJ-Base#126]
Hello, not sure how to fix this bug from spamming my server console and I think its my lag issue. 

[vjbase] addons/vjbase/lua/entities/npc_vj_creature_base/init.lua:1192: attempt to call method 'GetBoneFollowers' (a nil valu
e)
  1. unknown - addons/vjbase/lua/entities/npc_vj_creature_base/init.lua:1192
 
Timer Failed! [Simple][@addons/vjbase/lua/entities/npc_vj_creature_base/init.lua (line 1183)]

**Comment by ZombieWars** [comment]
![image](https://github.com/user-attachments/assets/c25ec76f-cff2-4dbd-8e1f-743a5520b3aa)

**Comment by DrVrej** [comment]
Please don't use the GitHub version on the regular GMod branch, it's meant to be used with the upcoming version. Use the dev branch if you want to use the GitHub version.

**Comment by ZombieWars** [comment]
Thank you!
