### ISSUE TITLE
Incredibly fucking shady.

### ISSUE THREAD

**Issue by kernaltrap8** [DrVrej/VJ-Base#129]
I probably installed this mod because it was in a collection my friend made, I had removed it as I had way too many addons. Opened GMod and was presented with this:
![image](https://github.com/user-attachments/assets/b5f4ae97-6ad1-4c56-9284-d3af4e412186)
This is INCREDIBLY fucking shady coming from someone who has looked at infostealer malware and the like. Please give me a reasonable explanation for this behavior. I will be looking into the source code to see exactly why this is even needed. Absurd.

**Comment by DrVrej** [comment]
Yes, an addon with almost 3 million active subscribers and over 10+ years old includes a virus. Congratulations you have managed to find the hidden malware that no one else has all these years!! 🎉

**Comment by kernaltrap8** [comment]
> Yes, an addon with almost 3 million active subscribers and over 10+ years old includes a virus. Congratulations you have managed to find the hidden malware that no one else has all these years!! 🎉

My apologize, this was done by a different addon, and was because it was redirecting to a Google Sites page.
![image](https://github.com/user-attachments/assets/415e8a8e-fc0c-4d85-8caf-84d2f26c4388)

**Comment by kernaltrap8** [comment]
> > Yes, an addon with almost 3 million active subscribers and over 10+ years old includes a virus. Congratulations you have managed to find the hidden malware that no one else has all these years!! 🎉
> 
> My apologize, this was done by a different addon, and was because it was redirecting to a Google Sites page. ![image](https://private-user-images.githubusercontent.com/94473358/367556471-415e8a8e-fc0c-4d85-8caf-84d2f26c4388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNjkyOTMsIm5iZiI6MTcyNjM2ODk5MywicGF0aCI6Ii85NDQ3MzM1OC8zNjc1NTY0NzEtNDE1ZThhOGUtZmMwYy00ZDg1LThjYWYtODRkMmYyNmM0Mzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDAyNTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1M2Q2ZmEzYmQwYTI0OTM5NTNjMDIyYzRmZjM1ZmFlYjdmNGZmY2NjZTQzNmMwNTM3ODc5YjY0ZGQ3OGRkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxd8P5Fc5JbGn643n4dh-wJajMqs-EoopTweHZsvlI0)

I made a comment about this earlier but it didn't go through

**Comment by DrVrej** [comment]
That's a very outdated code that addons used to use many years ago, I recommend notifying the author to update to the latest version.
