### ISSUE TITLE
Aerial movetype doesn't work on human base

### ISSUE THREAD

**Issue by SgtFlexxx** [DrVrej/VJ-Base#13]
Trying to have an aerial npc with a ranged weapon. I couldn't figure out how I could do it with creature base since it seems it can't have a weapon(?) but I'm not sure since I'm new to this.

I tried this with the human base instead since I can spawn it with a weapon, but the movement seems broken and this error gets spammed as long as the NPC exists:

[VJ Base] lua/entities/npc_vj_human_base/init.lua:1377: attempt to call method 'AerialMove_Stop' (a nil value)
  1. VJ_TASK_IDLE_STAND - lua/entities/npc_vj_human_base/init.lua:1377
   2. DoIdleAnimation - lua/entities/npc_vj_human_base/init.lua:1461
    3. SelectSchedule - lua/entities/npc_vj_human_base/init.lua:2565
     4. unknown - lua/entities/npc_vj_human_base/schedules.lua:15

**Comment by DrVrej** [comment]
The human base doesn't have aerial base implemented at the moment, if you want a aerial NPC to be using a ranged weapon, rather than an attack, then you will have to code it yourself. It's possible though, but it will require advanced coding.

**Comment by SgtFlexxx** [comment]
Oh boy, sounds like it's gonna be a pain. Gonna give it a try

**Comment by SgtFlexxx** [comment]
Hrm, I would like to use a weapon since I'd like the player to be able to use it as well. Is it perhaps possible to make it use the human_base, and just offset it from the ground to make it appear to hover?

This is what I'm going for
https://www.youtube.com/watch?v=q7PvdQEkTQk&feature=youtu.be

**Comment by DrVrej** [comment]
You could try, but not sure if it will work. You could also make the weapon only for the player, and then just make the NPC it on death.

**Comment by SgtFlexxx** [comment]
I apologize if this isn't the place to keep posting questions, but I'm not sure where else. I've started working on this again and made a lot of progress.

However, the one thing I can't figure out is how to delay the gibbing when an NPC dies. Currently, I would desire if the NPC fell out of the air, waited a few seconds, and then blew up and gibbed.

I'm basically trying to recreate the effect of the NPC's on the right in this video when they die. https://youtu.be/zghs0VeaRLw?t=43

**Comment by SgtFlexxx** [comment]
Trying to get the NPC to look down at the enemy it's targeting, but can't get it to work. I assume it's because of something in the code that forces the angle of the NPC when it's targeting an enemy.

`function ENT:CustomOnThink() 
	if (IsValid(self:GetEnemy())) then
	local ang = self:GetAngles();
	local enemyPos = self:GetEnemy():GetPos()
	local myPos = self:GetPos()
	local distanceXY = math.Distance(enemyPos.x, enemyPos.y, myPos.x, myPos.y)
	local lookAt = math.atan(distanceXY/(myPos.z-enemyPos.z))
	ang.z = math.deg(lookAt)*-1
	self:SetAngles(ang)
	PrintMessage( 3, ang.z)
	end
end`

I know I might be miscalculating something, but it's not rotating at all. I can only get it to rotate when it's not targeting anything.

**Comment by DrVrej** [comment]
If you would like help with coding in general, you are welcome to join the Discord server
