### ISSUE TITLE
NPC_Reload is a nil value?

### ISSUE THREAD

**Issue by Weapon317** [DrVrej/VJ-Base#132]
Hi.

I am using the workshop version of VJ Base and this is what it keeps spitting out in the server console logs. Any idea why?

Kind regards,

[vj_base] addons/vj_base/lua/entities/npc_vj_human_base/init.lua:2751: attempt to call method 'NPC_Reload' (a nil value)
  1. unknown - addons/vj_base/lua/entities/npc_vj_human_base/init.lua:2751

**Comment by DrVrej** [comment]
Thanks for the report! Has been fixed in 704de1da2e9a48715d5aae84420349f40adc7d27, will be included in the revamp update.
