### ISSUE TITLE
Player Detection Issues When Toggling Ignore Players

### ISSUE THREAD

**Issue by epicplayer40** [DrVrej/VJ-Base#22]
Since the enemy detection update, SNPCs have had a few new issues arrise in relation to spotting players:

If a player disables Ignore Players while SNPCs are present, the SNPCs will not detect players when they should. Damaging the SNPC will cause it to act normally again and spot the player.

If the scenario above occurs and the same SNPCs detected a player enemy and then Ignore Players is enabled, the SNPCs will continue to chase and attack the player when they should forget about players once Ignore Players is enabled.

**Comment by DrVrej** [comment]
Are you using the latest commit? I fixed this issue in one of the latest commits that requires to use the GMod dev version

**Comment by DrVrej** [comment]
After some testing, this seems to have been fixed 👍
