### ISSUE TITLE
VJ Base enemies not working properly

### ISSUE THREAD

**Issue by Jakobtheraddude** [DrVrej/VJ-Base#23]
Whenever I spawn in an enemy from this addon it doesn't react to other npcs or players and my command bar gets spammed with errors that read out as this. [ERROR] addons/vj-base-master/lua/autorun/vj_entities.lua:488: attempt to call method 'SetIdealYawAndUpdate' (a nil value)
  1. FaceCertainEntity - addons/vj-base-master/lua/autorun/vj_entities.lua:488
   2. unknown - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:2071

Please help me! I've done all I can for re installing it extracting etc. But nothing works!

**Comment by DrVrej** [comment]
Invalid report, you aren't using GMod dev version. This is a non-existent bug.
