### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by deathking61** [DrVrej/VJ-Base#25]
when i spawn anything that needs VJ base i get this spammed in the console until its removed

[ERROR] addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:1448: attempt to call method 'GetEnemyLastKnownPos' (a nil value)
  1. VJ_TASK_CHASE_ENEMY - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:1448
   2. DoChaseAnimation - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:1600
    3. SelectSchedule - addons/vj-base-master/lua/entities/npc_vj_creature_base/init.lua:2649
     4. unknown - addons/vj-base-master/lua/entities/npc_vj_creature_base/schedules.lua:13

**Comment by DrVrej** [comment]
As the description states, you must not use the Chromium version of GMod.
