### ISSUE TITLE
Bodies of dead NPCs do not disappear

### ISSUE THREAD

**Issue by AKLFR** [DrVrej/VJ-Base#30]
Sorry, I got the wrong ticket. And so there really is no way to get dead NPC bodies to disappear on a dedicated server?
thanks in advance

**Comment by DrVrej** [comment]
Well as I explained, this isn't a bug, you either have a conflicting mod or you are trying to use the menu on a dedicated server.

**Comment by AKLFR** [comment]
Yes, I understood your explanations. I am on a dedicated server, is there a solution to make it work or is there really no way?

**Comment by DrVrej** [comment]
> Yes, I understood your explanations. I am on a dedicated server, is there a solution to make it work or is there really no way?

I don't run servers, but from what I know, you would need to put the commands in the cfg I think?
