### ISSUE TITLE
VJ Blaster and server crashes. (Workshop Release)

### ISSUE THREAD

**Issue by nicolaspackham** [DrVrej/VJ-Base#31]
I haven't tested with any other weapons but the VJ Blaster, I would say we have a pretty well optimized server. However, when spawning a VJ Base NPC with the VJ Blaster on the server, it almost immediately crashes.

Steps to reproduce,
- Have a server.
- Spawn one or multiple VJ Base NPC's with the VJ Blaster.
- You'll soon either have the server stuck or crash it.
- This does not occur with VJ Base NPC's not using default VJ Base weapons.

**Comment by DrVrej** [comment]
Thank you for the report, here are my thoughts on this:
- Test it with other VJ weapons, you mention `not using default VJ Base weapons`, do you mean the blaster only?
- Remember that crashing has nothing to do with optimization, an instant crash means it's an error not an issue with resource management.
- I have never seen a crash report like this, let alone an specific weapon. I am not sure what you would like me to do in this case, my guess is good as yours. It could be a conflicting addon or just some weird issue with the game itself. Crash log might help, post it so I can take a look.
