### ISSUE TITLE
Vj base eyes error bug

### ISSUE THREAD

**Issue by abizeyshn** [DrVrej/VJ-Base#32]
When i use vj controller on nps, logs say this;
```
lua/entities/obj_vj_bullseye.lua:79: attempt to call method 'VJ_DoSetEnemy' (a nil value)
   1. unknown - lua/entities/obj_vj_bullseye.lua:79
```
![20210305151325_1](https://user-images.githubusercontent.com/80100339/110115126-b47cb380-7dc6-11eb-850d-f4f5d1888e0e.jpg)

**Comment by DrVrej** [comment]
Which NPCs did you test this with?

**Comment by DrVrej** [comment]
Tested with VJ NPCs and HL2 NPCs, no such errors. Provide the exact NPC you encountered this error, thank you.
