### ISSUE TITLE
the editors don't work and they apear as errors and i know it's from vjbase because i removed it from the addons list and it worked, i tested it with workshop vjbase it has the same problem

### ISSUE THREAD

**Issue by Loganm2007** [DrVrej/VJ-Base#33]
ERROR] gamemodes/sandbox/entities/entities/edit_fog.lua:13: attempt to call field 'Initialize' (a nil value)
1. unknown - gamemodes/sandbox/entities/entities/edit_fog.lua:13
2. Spawn - [C]:-1
3. SpawnFunction - gamemodes/sandbox/entities/entities/base_edit.lua:31
4. Spawn_SENT - gamemodes/sandbox/gamemode/commands.lua:758
5. unknown - gamemodes/sandbox/gamemode/commands.lua:823
6. unknown - lua/includes/modules/concommand.lua:54

**Comment by DrVrej** [comment]
This is invalid, VJ Base has over million users, many people would have reported such issue. But I took your word for it and tested anyway.

**Results**: No issues at all, everything works normally and no errors at all.
![image](https://user-images.githubusercontent.com/6934542/110197617-c4be7e00-7e1a-11eb-8d35-0d39dc394ee6.png)
