### ISSUE TITLE
VJBase requireing to sign in to google account

### ISSUE THREAD

**Issue by PipaEntertainment** [DrVrej/VJ-Base#37]
I was playing with my friend in the afternoon.
I didn't had VJ base installed and Garry's Mod Just gave me a pop up window that said "VJBase is not installed"
And then prompted me to sign in to my google account.
Please Help!
What is the problem?!

**Comment by Dragoteryx** [comment]
> What is the problem?!

There's your problem:
> I didn't had VJ base installed

**Comment by DrVrej** [comment]
Reason why you got that notification is because you have a VJ mod installed, but you have not installed VJ Base itself. As for the Google sign-in, it happened because the Google site page was disabled. I have reenabled the page, that issue is now be fixed.
