### ISSUE TITLE
SetNearestPointToEnitityPosition Error

### ISSUE THREAD

**Issue by jake0715** [DrVrej/VJ-Base#40]
![setnearestpointerror](https://user-images.githubusercontent.com/11466986/119574948-1a942980-bd6b-11eb-99c0-c774e365bb98.PNG)

Tried with battlefront 2 classic NPCs, WW2 NPCs, and ARVN/VC NPCs. Same error each time.

**Comment by DrVrej** [comment]
Please post a picture of the details that are found in "DrVrej/Installed Plugins" (On the right side of the spawn menu)

**Comment by jake0715** [comment]
![image](https://user-images.githubusercontent.com/11466986/119599970-e3d60780-bd9a-11eb-965d-6d573dc356a9.png)

**Comment by DrVrej** [comment]
You are running on an extremely old version of VJ Base. 2.6.2 was released many years ago. Where did you download VJ Base from?! You should only be downloading it from the official workshop page or through this GitHub repository.

**Comment by jake0715** [comment]
wait really
i downloaded it from the steam workshop. I even uninstalled and reinstalled, the game and the addon.

**Comment by DrVrej** [comment]
> wait really
> i downloaded it from the steam workshop. I even uninstalled and reinstalled, the game and the addon.

Weird, the version in your picture is from 2018, it makes sense now why those errors were appearing for you
