### ISSUE TITLE
in half life resugreinate or however you pronounce it Xen and Race X portals don`t work

### ISSUE THREAD

**Issue by Jaycey64** [DrVrej/VJ-Base#41]
when i try to spawn them, nothing happens.

**Comment by DrVrej** [comment]
1. Wrong repository.
2. They work, you are simply refusing to read the notification on spawn.

**Comment by Jaycey64** [comment]
> 1. Wrong repository.
> 2. They work, you are simply refusing to read the notification on spawn.

there is no notification on spawn, nothing happens
