### ISSUE TITLE
still don`t work :I

### ISSUE THREAD

**Issue by Jaycey64** [DrVrej/VJ-Base#42]
1. Wrong repository.
2. They work, you are simply refusing to read the notification on spawn.

_Originally posted by @DrVrej in https://github.com/DrVrej/VJ-Base/issues/41#issuecomment-851683476_
there is no notification on spawn, nothing happens, also i can`t talk or report anything on the right repository

**Comment by DrVrej** [comment]
Just checked, everything works 100%, example:
![image](https://user-images.githubusercontent.com/6934542/121294916-2845c500-c8bc-11eb-95fb-cd3d60d323ed.png)
