### ISSUE TITLE
Just checked, everything works 100%, example:

### ISSUE THREAD

**Issue by Jaycey64** [DrVrej/VJ-Base#43]
Just checked, everything works 100%, example:
![image](https://user-images.githubusercontent.com/6934542/121294916-2845c500-c8bc-11eb-95fb-cd3d60d323ed.png)

_Originally posted by @DrVrej in https://github.com/DrVrej/VJ-Base/issues/42#issuecomment-857368870_

doesn`t work for me.

**Comment by Jaycey64** [comment]
https://user-images.githubusercontent.com/80467027/121457996-977fef80-c976-11eb-92ac-095813d1eac8.mp4

heres what happens

**Comment by DrVrej** [comment]
In that case, I recommend you to wait until full release on Steam Workshop. The issue makes no sense at all, it's not possible for it to not work. Nothing else I can do to help you here.

Btw, you don't need to open a new issue every time, you can simply comment on the same one even if I close it.

**Comment by Jaycey64** [comment]
okay.

**Comment by Jaycey64** [comment]
> In that case, I recommend you to wait until full release on Steam Workshop. The issue makes no sense at all, it's not possible for it to not work. Nothing else I can do to help you here.
> 
> Btw, you don't need to open a new issue every time, you can simply comment on the same one even if I close it.

when do you think it will fully release on the work shop?

**Comment by DrVrej** [comment]
Hopefully sometime during this summer 👍
