### ISSUE TITLE
Does VJ Base work with Navmesh?

### ISSUE THREAD

**Issue by RiggsMackay** [DrVrej/VJ-Base#46]
I just want to make sure that I'm correct or wrong, because I heard you could make it so the NPCs use Navmesh instead of general AI Nodes, is that a setting in game or not? Thanks anyway.

**Comment by DrVrej** [comment]
AI Nodes only.

**Comment by Cpt-Hazama** [comment]
To elaborate more on this, VJ Base by default only uses AI Nodes. However, if you know what you're doing, you can easily add Nav-Mesh support to VJ Base.

By following the GMod tutorial (https://wiki.facepunch.com/gmod/Simple_Pathfinding), it is very easy to add Nav-Mesh support to any SNPC base. Again, I only recommend you attempt this if you know what you're doing, as VJ Base was never designed to work with Nav-Mesh to begin with you could easily break it.
