### ISSUE TITLE
"mouth" Pose parameter resets itself when a npc using hl1 (original, source) models speaks

### ISSUE THREAD

**Issue by Seamusmario** [DrVrej/VJ-Base#53]
while working on my hl2 snpcs addon (i am mostly remaking the entire addon), when i assigned the original sounds for the scientist, it wasn't able to move it's mouth when it was speaking.

**Comment by DrVrej** [comment]
That is done through the model itself, not through Lua. I recommend checking out HL2 citizen / main character models to see how Valve made their mouths move. 👍
