### ISSUE TITLE
Help, how do I separate the settings gui for VJ Base and CAP

### ISSUE THREAD

**Issue by RowanSkie** [DrVrej/VJ-Base#58]
So, I have a problem with this mod, and that is the fact that when I enter CAP's settings, it redirects to this one, specifically the "general" settings of Carter Addon Pack.

Got any way for me to fix it?

**Comment by DrVrej** [comment]
I have no idea what CAP is, this is VJ Base, if other mods are doing something wrong, it has nothing to do with this mod. This is a mod that contains different types of bases for other modders to use to create their own mods.

**Comment by RowanSkie** [comment]
CAP = Carter Addon Pack, though?

**Comment by DrVrej** [comment]
VJ Base is completely standalone, and I make sure of that. It's the reason why it gained popularity very quickly. If something is overlapping with VJ Base, then it's the fault of the other mod. I suggest contacting the author of that mod.

**Comment by RowanSkie** [comment]
Okay, I checked my game again with CAP and VJ Base installed.

Basically, CAP has "Client Settings" that I can access, but when I click it, it redirects to VJ Base's "Client Settings". My plan is actually just to make it that I edit CAP so I don't have to actually make you change it, but uh... I don't know where.

**Comment by DrVrej** [comment]
I don't even know how the author of that mod managed to do that, if somehow he managed to name the hooks exactly the same, then he must have simply copied the code from here and probably forgot to change the name. Everything in this base is prefixed with "VJ_", so the chance of confliction is 0 unless code was copied from here.
