### ISSUE TITLE
NPCs have no collision, making them immune to my gunfire

### ISSUE THREAD

**Issue by G-Howsam** [DrVrej/VJ-Base#60]
For some reason I can't pinpoint, the NPCs suddenly have no collision, and it makes them invincible against guns that I shoot. Only guns that spawn an actual entity like the AR2 ball or any form of RPG can damage them.

I don't know if it's an addon problem since it worked when I loaded the map initially.

As a 'bonus', it seems to be occurring with EVERY OTHER NPC, including the ones in the base game. I can't find anything about it.

**Comment by DrVrej** [comment]
Sorry but this has nothing to do with VJ Base, you are reporting it on the wrong repository.
