### ISSUE TITLE
Updating SNPC Relation ship with a specific player through code.

### ISSUE THREAD

**Issue by RiggsMackay** [DrVrej/VJ-Base#66]
I've been having a hard time making the VJ base SNPC's friendly towards teams in my gamemode, though with using AddEntityRelationship I've had no luck. I was wondering if there is a way to even do it?

Here is the code I've used, It works with the base NPCs although not with the VJ Base SNPC's, help would be appreciated!
https://prnt.sc/qXgOiu9xId0i

**Comment by DrVrej** [comment]
Answered on Discord
