### ISSUE TITLE
Npc's unfreezing peoples props causing annoyance.

### ISSUE THREAD

**Issue by wrefgtzweve** [DrVrej/VJ-Base#75]
Running vjbase on a server and npcs keep unfreezing people's stuff when they're building.
Could there be a convar to disable this behaviour?

Code in question:
https://github.com/DrVrej/VJ-Base/blob/728ee9d103797ae523e0be599a537b3c33a405f4/lua/entities/npc_vj_creature_base/init.lua#L2141

**Comment by charitea** [comment]
A convar would be useful if implemented, it's annoying that it's unconfigurable.
