### ISSUE TITLE
Serverside lua error

### ISSUE THREAD

**Issue by wrefgtzweve** [DrVrej/VJ-Base#76]
We've been getting this serverside Lua error pretty frequently, doesn't seem like a big issue but it's been going on for a while so i might as well report it. I do not know how to replicate it.
```
[ERROR] lua/vj_base/npc_schedules.lua:155: attempt to call method 'VJ_TASK_IDLE_STAND' (a nil value)
  1. RunCode_OnFail - lua/entities/npc_vj_creature_base/init.lua:1451
    2. DoRunCode_OnFail - lua/vj_base/npc_schedules.lua:143
      3.  - lua/vj_base/npc_schedules.lua:155
```

**Comment by DrVrej** [comment]
This bug has been present for a while, it's harmless. Basically Lua is failing to recognize the function at random instances. I have found no way of replicating this, making it extremely difficult to fix (if even possible).

**Comment by wrefgtzweve** [comment]
It's only being set when `doLOSChase` is false, otherwise it's being skipped (i think)
![image](https://user-images.githubusercontent.com/69946827/177230108-70c86185-6303-42f8-9b28-1e2820e16d7d.png)

**Comment by wrefgtzweve** [comment]
https://github.com/DrVrej/VJ-Base/blob/6344186d517d9371878d2ce6bf04b45b49381242/lua/vj_base/npc_schedules.lua#L156
Could be simplified to make sure the error doesn't happen anymore
![image](https://user-images.githubusercontent.com/69946827/177230246-188adfde-50b9-4173-a794-85b7f29deab7.png)

**Comment by DrVrej** [comment]
Setting that there won't change anything, the issue is that Lua thinks `self:VJ_TASK_IDLE_STAND()` is nil, a check like this could possibly solve it:
```
task_chaseEnemy.RunCode_OnFail = function() if self.VJ_TASK_IDLE_STAND then self:VJ_TASK_IDLE_STAND() end end
```
But this is an ugly solution

**Comment by DrVrej** [comment]
Added fail safe in d9881b077bae863a8eefef5e21b5a84024676026, hopefully this will fix it
