### ISSUE TITLE
Strange shotgun reloads.

### ISSUE THREAD

**Issue by ToastedBraincell** [DrVrej/VJ-Base#78]
The player-usable Shotgun in VJ Base seems to reload to full after loading just one shell. This only seems to affect players, since I'm not sure if NPCs even use reload timers.

**Comment by Cpt-Hazama** [comment]
The weapons are for NPCs, this is stated in the addon. NPCs don't rely on single shell reloading so that isn't going to be coded

**Comment by ToastedBraincell** [comment]
alright
