### ISSUE TITLE
Allow to disable changing targetname of entity in Initialize() to self.PrintName

### ISSUE THREAD

**Issue by URAKOLOUY5** [DrVrej/VJ-Base#83]
I'm making somekind of support for my SNPCS for scripted_sequence entity and think this is will be better if there was a `self.OverrideTargetName` condition for this line in base npcs:

```lua
self:SetName((self.PrintName == "" and list.Get("NPC")[self:GetClass()].Name) or self.PrintName)
```

so:

```lua
if self.OverrideTargetName then
self:SetName((self.PrintName == "" and list.Get("NPC")[self:GetClass()].Name) or self.PrintName)
end
```

I know I can revert name back to K/V of targetname, but this idea is better.

**Comment by DrVrej** [comment]
Thanks for reporting this issue! It has been fixed in e8a0fa2 and will be included in the next update!
