### ISSUE TITLE
Constant Errors and Crashes

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [DrVrej/VJ-Base#87]
In terms of the VJ Base on the Steam Workshop for Garry's Mod, I am still getting constant errors despite the contradicting addons being disabled. I can't tell if this is all the custom addons' issues, or if its entirely on VJ Base, but care to overhaul the addon so these issues won't bombard the game to the point of crashing? Because sometimes it can whenever I use the Global NPC Spawner.

**Comment by DrVrej** [comment]
I am not entirely sure what the purpose of this post was, no information was offered. I ask you kindly to please follow the guidelines on GitHub, as it specifically says to post the errors and ways to reproduce it, thank you.
