### ISSUE TITLE
Hitscan enemies aim above their enemy's head

### ISSUE THREAD

**Issue by LOL-DUDE-64** [DrVrej/VJ-Base#88]
Thus missing all of their shots entirely. This happens both when NPCs target other NPCs or players. The strange part is that their spread also seems to be turned all the way down, so even NPCs with shotguns land all of their bullets in one point above their target's head. I'm on the 64-bit branch of Garry's Mod.

**Comment by DrVrej** [comment]
That is caused by a conflicting mod, not an issue with VJ Base or Garry's Mod. If you find which mod is causing it, please send it to me so I can add it to this list: https://steamcommunity.com/sharedfiles/filedetails/?id=1129493108
Thank you.

**Comment by LOL-DUDE-64** [comment]
I found that it's solely caused by [PrikolMen:-b](https://steamcommunity.com/id/PrikolMen) and [Klen_list](https://steamcommunity.com/id/klen_list)'s [Random Patches v3.2.0](https://steamcommunity.com/sharedfiles/filedetails/?id=2806290767).

**Comment by DrVrej** [comment]
Thank you for the report, I have added it to the list, the author is unfortunately overriding default functions without much care.

**Comment by klen-list** [comment]
This issue should be fixed after latest update of Random Patches (v3.5.0)

**Comment by klen-list** [comment]
@DrVrej can you remove our addon from your list? That bug is fixed.
