### ISSUE TITLE
Error with GetMaxLookDistance

### ISSUE THREAD

**Issue by Crouipy** [DrVrej/VJ-Base#93]
Do you know about this error? It causes our snpc's to not attack and it appears when we try to spawn whatever npc from the vjbase:
![image](https://user-images.githubusercontent.com/126088576/220656625-15824315-0fb4-4200-b86d-fc9e7f261d54.png)

**Comment by DrVrej** [comment]
You shouldn't ignore the message VJ Base posts when you load into a map: Just stop using the outdated abandoned chromium branch.
