### ISSUE TITLE
NPCs don't attack

### ISSUE THREAD

**Issue by BGiPV** [DrVrej/VJ-Base#95]
NPCs run around the map, stand, but do not attack players. This happens to different NPCs from different addons. And the following error will appear in the console.

```
[VJ Base] lua/vj_base/npc_general.lua:1286: attempt to call method 'GetMaxLookDistance' (a nil value)
  1. SetupRelationships - lua/vj_base/npc_general.lua:1286
   2. unknown - lua/entities/npc_vj_creature_base/init.lua:1900
```

**Comment by DrVrej** [comment]
You are using either an outdated GMod version (Chromium) or a pirated version which tends to be outdated too.
